CREATE TABLE dislike (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	userId INTEGER NOT NULL,
	dislikeId INTEGER NOT NULL,
	FOREIGN KEY (userId) REFERENCES user (id),
	FOREIGN KEY (dislikeId) REFERENCES user (id)
);
