# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in `frontend` directory
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10000
    reviewers:
      - "AudeizReading"
    assignees:
      - "AudeizReading"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      angular-minor-and-patch:
        applies-to: security-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        applies-to: version-updates
        patterns:
          - "*eslint*"
        update-types:
          - "minor"
          - "patch"
      eslint-minor-and-patch:
        applies-to: security-updates
        patterns:
          - "*eslint*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*eslint*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    # Files stored in `backend` directory
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10000
    reviewers:
      - "louchebem06"
    assignees:
      - "louchebem06"
    groups:
      nestjs-core:
        applies-to: version-updates
        patterns:
          - "@nestjs/common"
          - "@nestjs/config"
          - "@nestjs/core"
          - "@nestjs/jwt"
          - "@nestjs/platform-express"
          - "@nestjs/platform-socket.io"
          - "@nestjs/websockets"
        update-types:
          - "major"
          - "minor"
          - "patch"
      docs:
        applies-to: version-updates
        patterns:
          - "@nestjs/swagger"
          - "nestjs-asyncapi"
        update-types:
          - "major"
          - "minor"
          - "patch"
      database:
        applies-to: version-updates
        patterns:
          - "sqlite3"
        update-types:
          - "major"
          - "minor"
          - "patch"
      testing:
        applies-to: version-updates
        patterns:
          - "jest*"
          - "supertest"
          - "ts-jest"
        update-types:
          - "major"
          - "minor"
          - "patch"
      auth-security:
        applies-to: version-updates
        patterns:
          - "bcrypt*"
          - "@types/bcrypt*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      transpilation:
        applies-to: version-updates
        patterns:
          - "typescript"
          - "ts-node"
          - "ts-loader"
          - "tsconfig-paths"
        update-types:
          - "major"
          - "minor"
          - "patch"
      media-utils:
        applies-to: version-updates
        patterns:
          - "fluent-ffmpeg"
          - "music-metadata"
          - "image-size"
        update-types:
          - "major"
          - "minor"
          - "patch"
      uuid:
        applies-to: version-updates
        patterns:
          - "uuid*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      linting-formatting:
        applies-to: version-updates
        patterns:
          - "*eslint*"
          - "prettier*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10000
    reviewers:
      - "louchebem06"
      - "AudeizReading"
    assignees:
      - "louchebem06"
      - "AudeizReading"
